import type { Talk } from "./talks";

type PrototypeKind = "upcoming" | "previous";

const titles: Record<PrototypeKind, string[]> = {
  upcoming: [
    "Porosity and dimension in random self-similar sets",
    "Thermodynamic formalism for non-uniformly expanding maps",
    "Furstenberg measures and stationary fractal distributions",
    "Assouad spectra of dynamically defined carpets",
    "Rigidity phenomena for conformal iterated function systems",
    "Shrinking targets in symbolic dynamics",
    "Fourier decay for nonlinear Cantor measures",
    "Multifractal analysis of Birkhoff averages",
    "Projections of planar self-affine measures",
    "Recurrence rates and local dimension",
    "Fractal uncertainty principles in open dynamics",
    "Dimension conservation beyond exact overlaps",
  ],
  previous: [
    "Entropy and dimension for skew-product systems",
    "Exceptional directions in Marstrand projection theory",
    "Julia sets near parabolic parameters",
    "Random walks on groups of circle diffeomorphisms",
    "Distance sets of Ahlfors-regular fractals",
    "Symbolic codings for hyperbolic attractors",
    "CP-chains and scenery flow",
    "Lattice versus non-lattice self-similar geometry",
    "Escape rates for intermittent maps",
    "Fractal percolation with dependent retention",
    "Dimension drop under arithmetic resonance",
    "Harmonic measure on planar domains",
    "Lyapunov exponents for matrix cocycles",
    "Kakeya-type problems over product Cantor sets",
    "Counting periodic orbits by geometric size",
    "Quasisymmetric distortion of metric boundaries",
    "Bernoulli convolutions and algebraic parameters",
    "Visible parts of random fractals",
    "Pressure metrics on deformation spaces",
    "Measures of maximal dimension for solenoids",
    "Diophantine approximation on fractal sets",
    "Spectral gaps for transfer operators",
    "Tangent measures and local geometry",
  ],
};

const speakers = [
  ["Maya Levin", "Technion"],
  ["Noam Barak", "Hebrew University of Jerusalem"],
  ["Elena Rossi", "University of Pisa"],
  ["Daniel Kim", "KAIST"],
  ["Lea Martin", "Université Paris-Saclay"],
  ["Amir Cohen", "Tel Aviv University"],
  ["Sofia Almeida", "University of Porto"],
  ["Jonas Weber", "University of Bonn"],
  ["Rina Sato", "Kyoto University"],
  ["Ethan Miller", "University of Warwick"],
  ["Nora Feldman", "Weizmann Institute of Science"],
  ["Omar Haddad", "University of Haifa"],
  ["Clara Nguyen", "ETH Zürich"],
  ["Samuel Price", "University of Bristol"],
  ["Yael Shavit", "Ben-Gurion University"],
] as const;

const venues = [
  "RM 864, Amado",
  "RM 814, Amado",
  "RM 232, Amado",
  "RM 201, Taub",
  "RM 617, Meyer",
];

const starts = ["14:30", "15:00", "16:00", "12:30", "14:00", "16:30"];
const durations = [60, 60, 90, 60, 90, 60];

const summaries = [
  "We study how local porosity controls several notions of dimension and explain why the random setting exhibits sharper thresholds than deterministic constructions.",
  "This talk develops a pressure-based description of irregular orbit growth, with applications to equilibrium states and dimension spectra for expanding dynamical systems.",
  "We connect stationary measures, magnification dynamics, and entropy growth to obtain new dimension bounds for measures generated by random products.",
  "The focus is the fine-scale geometry of self-affine carpets and the phase transitions that appear when the observation scale changes anisotropically.",
  "We discuss when geometric data determine a conformal fractal system up to a smooth change of coordinates, and where flexibility can still occur.",
  "Shrinking-target sets provide a meeting point for recurrence, probability, and metric number theory. We describe their size through dynamical covering arguments.",
  "We present mechanisms that force cancellation in the Fourier transform of singular measures and relate them to nonlinear distortion across scales.",
  "Birkhoff averages produce level sets with rich geometry. A variational principle turns their entropy and Lyapunov data into a multifractal spectrum.",
  "We examine how planar self-affine measures behave under projection, highlighting the roles of eccentricity, resonance, and exceptional directions.",
  "Return times reveal the local geometry of an invariant measure. The talk compares recurrence exponents with pointwise dimension in several model systems.",
  "Open hyperbolic systems leave behind fractal trapped sets. We explain how their geometry yields uncertainty estimates and spectral consequences.",
  "Exact overlaps are only one cause of dimension loss. We explore broader concentration mechanisms and criteria that preserve dimension under nonlinear maps.",
];

const addMinutes = (start: string, minutes: number) => {
  const [hour, minute] = start.split(":").map(Number);
  const total = hour * 60 + minute + minutes;
  return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`;
};

export const expandPrototypeTalks = (sources: Talk[], count: number, kind: PrototypeKind): Talk[] => {
  if (sources.length === 0) return [];

  const anchor = kind === "upcoming"
    ? new Date("2026-10-08T14:30:00+03:00")
    : new Date("2026-05-28T14:30:00+03:00");

  return Array.from({ length: count }, (_, index) => {
    const source = sources[index % sources.length];
    const date = new Date(anchor);
    date.setDate(anchor.getDate() + (kind === "upcoming" ? index * 7 : index * -7));

    const start = starts[(index + (kind === "previous" ? 2 : 0)) % starts.length];
    const [hour, minute] = start.split(":").map(Number);
    date.setHours(hour, minute, 0, 0);
    const [speaker, affiliation] = speakers[(index * 2 + (kind === "previous" ? 3 : 0)) % speakers.length];

    return {
      ...source,
      id: `${kind}-${index + 1}`,
      data: {
        ...source.data,
        title: titles[kind][index],
        speaker,
        affiliation,
        date,
        endTime: addMinutes(start, durations[index % durations.length]),
        venue: venues[(index * 3 + (kind === "previous" ? 1 : 0)) % venues.length],
        summary: summaries[(index + (kind === "previous" ? 4 : 0)) % summaries.length],
      },
    };
  }).sort((a, b) => b.data.date.getTime() - a.data.date.getTime());
};
